### ISSUE TITLE
LAZIOUSDT - TypeError: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by jarrodjay** [cdalton713/trading-bot-new-coins#10]
Something weird happened with LAZIO. I'm set to purchase 40 USDT. It instead grabbed 72.1USDT (price at 70USDT, flat). Candle stick looks weird too- L of 1, flat, and H of 100, flat. So not only did it purchase higher than my set limit, it also looks odd with the initial price. 
It also errored out.
```
[ERROR] 2021-10-21 12:00:00,278: PROCESSING NEW TICKER:
{"ticker": "LAZIOUSDT", "base_ticker": "LAZIO", "quote_ticker": "USDT"}.
[ERROR] 2021-10-21 12:00:00,278: [BINANCE]      Preparing to buy LAZIOUSDT.
[ERROR] 2021-10-21 12:00:01,106: [BINANCE]      Placing [LIVE] Order...
[ERROR] 2021-10-21 12:00:01,580: Traceback (most recent call last):
  File "/root/trading-bot-new-coins/bot/bot.py", line 279, in process_new_ticker
    order = self.broker.place_order(
  File "/root/trading-bot-new-coins/broker/broker.py", line 292, in place_order
    fill_sum += (fill['price'] - fill['commission'])
TypeError: unsupported operand type(s) for -: 'str' and 'str'
.
```

**Comment by cdalton713** [comment]
Removed Pydantic features since it slowed things down a bit.

**Comment by cdalton713** [comment]
Removed Pydantic features since it slowed things down a bit.
