### ISSUE TITLE
Issue with FIDAUSDT

### ISSUE THREAD

**Issue by jarrodjay** [cdalton713/trading-bot-new-coins#5]
I'm a bit confused with what happened. I had it set to buy 50 usdt. (had enough in my spot wallet). In my trade history, I can see that I purchased 7.4 FIDA at 6.8 USDT (roughly $50). However, bot is telling me I didn't purchase due to insufficient funds. It also didn't store a trade, so didn't sell. Thoughts?

```
[DEBUG] 2021-09-30 12:00:00,729: PROCESSING NEW TICKER:
{"ticker": "FIDAUSDT", "base_ticker": "FIDA", "quote_ticker": "USDT"}.
[DEBUG] 2021-09-30 12:00:00,730: [BINANCE]      Preparing to buy FIDAUSDT.
[DEBUG] 2021-09-30 12:00:01,788: [BINANCE]      Placing [LIVE] Order...
```

```
[ERROR] 2021-09-30 12:00:05,101: Traceback (most recent call last):
  File "/root/trading-bot-new-coins/bot/bot.py", line 272, in process_new_ticker
    self.config, ticker=new_ticker, size=size, side="BUY", **kwargs
  File "/usr/local/lib/python3.6/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/trading-bot-new-coins/util/decorators.py", line 113, in retry_decorator
    logger,
  File "/root/trading-bot-new-coins/util/decorators.py", line 41, in __retry_internal
    return f()
  File "/root/trading-bot-new-coins/broker/broker.py", line 280, in place_order
    api_resp = super(Binance, self).create_order(**params)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 1387, in create_order
    return self._post('order', True, data=params)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 374, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
```

**Comment by cdalton713** [comment]
To clarify, the purchase **did** go through on Binance's side, despite the bot giving the `Account has insufficient balance for requested action.` error?

**Comment by cdalton713** [comment]
Removing the `retry` option from purchases.  I'm thinking the coin was correctly purchased but the method was retried for a second time for some reason, which is when you got this message.
